# Generated by Django 5.2.4 on 2025-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hosuses/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('head_of_house', models.CharField(max_length=100)),
                ('total_members', models.PositiveIntegerField()),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
