# Generated by Django 5.2.4 on 2025-07-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hosuse',
        ),
    ]
