# Generated by Django 5.2.4 on 2025-07-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='programs',
            name='spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
